/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-01-11 08:42:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class buy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'buy.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("    \t\tfunction test(){\r\n");
      out.write(" var url = \"buy\";\r\n");
      out.write(" window.location.href= url;\r\n");
      out.write("}\r\n");
      out.write("    function Check(){\r\n");
      out.write("   \r\n");
      out.write("   var n1=document.getElementById(\"bagweight\").value;\r\n");
      out.write("   var n2=document.getElementById(\"op\").value;\r\n");
      out.write("   var n3=document.getElementById(\"date\").value;\r\n");
      out.write("   var n4=document.getElementById(\"addresstext\").value;\r\n");
      out.write(" \r\n");
      out.write("      var n5=document.getElementById(\"nametext\").value;\r\n");
      out.write("      var n6=document.getElementById(\"price\").value;\r\n");
      out.write("       var n7=document.getElementById(\"bag\").value;\r\n");
      out.write("      var erroring=\"\";\r\n");
      out.write(" \r\n");
      out.write("      if(n1==\"\"||n1==null){\r\n");
      out.write("        erroring+=\"请输入每袋小麦重量!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n2==\"\"||n2==null){\r\n");
      out.write("     erroring+=\"请输入客户编号!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n3==\"\"||n3==null){\r\n");
      out.write("  erroring+=\"请输入日期!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n4==\"\"||n4==null){\r\n");
      out.write("  erroring+=\"请输入客户地址!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n5==\"\"||n5==null){\r\n");
      out.write("  erroring+=\"请输入客户姓名!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  if(n6==\"\"||n6==null){\r\n");
      out.write("  erroring+=\"请输入加工费!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write("   if(n7==\"\"||n7==null){\r\n");
      out.write("  erroring+=\"请输小麦袋数!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write("  if(erroring.length!=0){\r\n");
      out.write("  alert(erroring);\r\n");
      out.write("  return false;\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  }else{\r\n");
      out.write("  alert(\"保存成功！\");\r\n");
      out.write("     document.form1.submit();    \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\t\t//弹出信息窗口\r\n");
      out.write("\t\tfunction showWindow(){\r\n");
      out.write("\r\n");
      out.write("\t\t\twindow.open ('otherinquireclient.jsp','add', \r\n");
      out.write("'height=600, width=800, top=60, left=200, toolbar=no,menubar=no,scrollbars=yes,resizable=no,location=no, status=no') ;\r\n");
      out.write("} \r\n");
      out.write("function add(){\r\n");
      out.write("\r\n");
      out.write("var bagweight=document.getElementById(\"bagweight\").value;\r\n");
      out.write("var bag=document.getElementById(\"bag\").value;\r\n");
      out.write("var sum=bagweight*bag;\r\n");
      out.write("var price=document.getElementById(\"price\").value\r\n");
      out.write("var sumprice=sum*price;\r\n");
      out.write("document.getElementById(\"sumbag\").value=sum;\r\n");
      out.write("document.getElementById(\"sumprice\").value=sumprice;\r\n");
      out.write("document.getElementById(\"pay\").value=sumprice;\r\n");
      out.write("document.getElementById(\"realpay\").value=sumprice;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function cha(){\r\n");
      out.write("var cha;\r\n");
      out.write("if(document.getElementById(\"pay\").value>document.getElementById(\"realpay\").value){\r\n");
      out.write("cha=document.getElementById(\"pay\").value-document.getElementById(\"realpay\").value;\r\n");
      out.write("//var select=document.getElementById(\"selectid\");\r\n");
      out.write("//var s=select.options[select.selectedIndex].value;\r\n");
      out.write("document.getElementById(\"cha\").value=cha;\r\n");
      out.write("document.getElementById(\"selectid\").value=3;\r\n");
      out.write("}\r\n");
      out.write("if(document.getElementById(\"pay\").value<document.getElementById(\"realpay\").value){\r\n");
      out.write("cha=document.getElementById(\"realpay\").value-document.getElementById(\"pay\").value;\r\n");
      out.write("//var select=document.getElementById(\"selectid\");\r\n");
      out.write("//var s=select.options[select.selectedIndex].value;\r\n");
      out.write("document.getElementById(\"cha\").value=cha;\r\n");
      out.write("document.getElementById(\"selectid\").value=2;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\t </script>\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"28278\",secure:\"28283\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  \r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-3\" data-genuitec-path=\"/Flour/WebRoot/buy.jsp\">\r\n");
      out.write("    <form action=\"addbuy\" id=\"form1\" name=\"form1\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-3\" data-genuitec-path=\"/Flour/WebRoot/buy.jsp\">\r\n");
      out.write("   \r\n");
      out.write("    <strong style=\"font-size:25px\">原粮兑换面粉|</strong>原粮购置\r\n");
      out.write("    \r\n");
      out.write("     <center>\r\n");
      out.write("    <table  border=\"1\" cellspacing=\"0\" bordercolor=\"#8EE1F6\" >\r\n");
      out.write("    <tr >\r\n");
      out.write("    <td  colspan=\"7\" width=\"600\" align=\"center\"  >原粮购置 </td>\r\n");
      out.write("   \r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">凭证编号：</td>\r\n");
      out.write("    <td  colspan=\"1\"  bgcolor=\"#f1f1f1\" ><input type=\"text\" name=\"buy.eid\"value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"readonly/></td>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\" >日期：</td>\r\n");
      out.write("    <td colspan=\"2\" ><input type=\"date\" name=\"buy.date\" id=\"date\" style=\"width:148px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <input type=\"hidden\" id=\"op\" name=\"bian\"/>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">供应商编号：</td>\r\n");
      out.write("    <td  colspan=\"1\"  bgcolor=\"#f1f1f1\" id=\"idtext\" ><input  type=\"button\" onclick=\"showWindow();\" value=\"获取\" /></td>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\" >供应商姓名：</td>\r\n");
      out.write("    <td  colspan=\"2\"  bgcolor=\"#f1f1f1\" ><input  id=\"nametext\" type=\"text\" readonly/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">供应商地址：</td>\r\n");
      out.write("    <td colspan=\"5\"  bgcolor=\"#f1f1f1\" ><input id=\"addresstext\" type=\"text\" readonly/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"7\" align=\"left\">交易明细</td>\r\n");
      out.write("    </tr> \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td align=\"center\"   bgcolor=\"#f1f1f1\">名称</td>\r\n");
      out.write("    \r\n");
      out.write("    <td align=\"center\"   bgcolor=\"#f1f1f1\">每袋重量</td>\r\n");
      out.write("    <td align=\"center\"   bgcolor=\"#f1f1f1\">袋数</td>\r\n");
      out.write("    <td align=\"center\"   bgcolor=\"#f1f1f1\">总重量</td>\r\n");
      out.write("    <td align=\"center\"   bgcolor=\"#f1f1f1\">单价￥</td>\r\n");
      out.write("    <td align=\"center\"   bgcolor=\"#f1f1f1\">总价￥</td>\r\n");
      out.write("    </tr> \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td align=\"center\" > <select >产品种类\r\n");
      out.write("    <option value=\"1\">产品 种类</option>\r\n");
      out.write("    <option value=\"2\">小麦</option>\r\n");
      out.write("  \r\n");
      out.write("    </select></td>\r\n");
      out.write("    \r\n");
      out.write("    <td ><input type=\"text\"name=\"buy.bagweight\" id=\"bagweight\" ></td>\r\n");
      out.write("    <td> <input type=\"text\" id=\"bag\" name=\"buy.bag\" ></td>\r\n");
      out.write("    <td onclick=\"add();\" align=\"center\"  bgcolor=\"#f1f1f1\"><input type=\"text\" id=\"sumbag\" name=\"buy.weight\"value=\"0\"readonly></td>\r\n");
      out.write("    <td><input type=\"text\" id=\"price\" name=\"buy.price\"></td>\r\n");
      out.write("    <td  onclick=\"add();\"bgcolor=\"#f1f1f1\"><input type=\"text\" id=\"sumprice\" value=\"0\" name=\"buy.sum\"></td>\r\n");
      out.write("    </tr> \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"7\">&nbsp</td>\r\n");
      out.write("    </tr> \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"7\" align=\"left\">交易信息</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">应付金额￥：</td>\r\n");
      out.write("    <td  colspan=\"1\"  bgcolor=\"#f1f1f1\"><input type=\"text\" id=\"pay\" value=\"0\" name=\"pay\"readonly/></td>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">实付金额￥：</td>\r\n");
      out.write("    <td colspan=\"2\" onclick=\"cha();\"><input type=\"text\" id=\"realpay\" value=\"0\" name=\"realpay\"readonly></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">收付状态：</td>\r\n");
      out.write("    <td align=\"left\"   bgcolor=\"#f1f1f1\"> <select id=\"selectid\" >收付平衡\r\n");
      out.write("                    <option  selected>收支平衡</option>\r\n");
      out.write("                    <option value=2>支大于收</option>\r\n");
      out.write("                    <option value=3>收大于支</option>\r\n");
      out.write("    </select></td>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\"   bgcolor=\"#f1f1f1\">收付差额￥：</td>\r\n");
      out.write("    <td colspan=\"2\"  bgcolor=\"#f1f1f1\"><input type=\"text\" id=\"cha\" value=\"0\" readonly/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("   <td align=\"center\" colspan=\"7\"> <input type=\"button\" onclick=\"Check();\"value=\"保存\" />  <input type=\"button\" value=\"取消\" onclick=\"test();\"/>\r\n");
      out.write("   \r\n");
      out.write("   </tr>\r\n");
      out.write("    \r\n");
      out.write("    </table>\r\n");
      out.write("  </center>\r\n");
      out.write("  \r\n");
      out.write("  </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
