/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-01-11 08:41:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class rawfoodinstore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1515652906491L));
    _jspx_dependants.put("jar:file:/E:/7组/.metadata/.me_tcat85/webapps/Flour/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279401888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'rawfoodinstore.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\tfunction test(){\r\n");
      out.write(" var url = \"rawfoodinstore\";\r\n");
      out.write(" window.location.href= url;\r\n");
      out.write("}\r\n");
      out.write("\t\t//弹出信息窗口\r\n");
      out.write("\t\t function show(obj){\r\n");
      out.write("       \r\n");
      out.write("        var x = window.screen.height;\r\n");
      out.write("    var y = window.screen.width;\r\n");
      out.write("    var h = 400;\r\n");
      out.write("    var w = 600;\r\n");
      out.write("    var model = \"title=word,resizable=yes,scrollbars=no,height=\" + h + \",width=\" + w + \",status=no,toolbar=no,menubar=no,location=no,top=\" + (x-h)/2 + \",left=\" + (y-w)/2;\r\n");
      out.write("    var url = \"\";\r\n");
      out.write("\r\n");
      out.write("    url = \"otherinquireclient.jsp\";//弹出窗口的页面内容\r\n");
      out.write("    var oOpen = window.open(url,\"add\",model);\r\n");
      out.write("    oOpen.focus();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("   function Check(){\r\n");
      out.write("   \r\n");
      out.write("   var n1=document.getElementById(\"rawstore\").value;\r\n");
      out.write("   var n2=document.getElementById(\"op\").value;\r\n");
      out.write("   var n3=document.getElementById(\"date\").value;\r\n");
      out.write("   var n4=document.getElementById(\"addresstext\").value;\r\n");
      out.write(" \r\n");
      out.write("      var n5=document.getElementById(\"nametext\").value;\r\n");
      out.write("   var erroring=\"\";\r\n");
      out.write(" \r\n");
      out.write("  if(n1==\"\"||n1==null){\r\n");
      out.write("  erroring+=\"请输入小麦重量!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write("  if(n2==\"\"||n2==null){\r\n");
      out.write("  erroring+=\"请输入客户编号!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n3==\"\"||n3==null){\r\n");
      out.write("  erroring+=\"请输入日期!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n4==\"\"||n4==null){\r\n");
      out.write("  erroring+=\"请输入客户地址!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n5==\"\"||n5==null){\r\n");
      out.write("  erroring+=\"请输入客户姓名!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if(erroring.length!=0){\r\n");
      out.write("  alert(erroring);\r\n");
      out.write("  return false;\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  }else{\r\n");
      out.write("  alert(\"保存成功！\");\r\n");
      out.write("     document.form1.submit();    \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" }  \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t </script>\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"28278\",secure:\"28283\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write(" \r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-26\" data-genuitec-path=\"/Flour/WebRoot/rawfoodinstore.jsp\">\r\n");
      out.write("   <form action=\"addinstore\" id=\"form1\" name=\"form1\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-26\" data-genuitec-path=\"/Flour/WebRoot/rawfoodinstore.jsp\">\r\n");
      out.write("<strong style=\"font-size:25px\">原粮兑换面粉</strong>|原粮入库\r\n");
      out.write("<center>\r\n");
      out.write("<table border=\"1\" cellspacing=\"0\" bordercolor=\"#8EE1F6\">\r\n");
      out.write("\r\n");
      out.write("\t<tr align=\"center\" >\r\n");
      out.write("\t\t<td colspan=\"4\" align=\"center\"><strong>原粮入库</strong></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t  \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" bgcolor=\"#f1f1f1\">凭证编号：</td>\r\n");
      out.write("\t\t<td bgcolor=\"#f1f1f1\"><input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"type=\"text\" name=\"instore.eid\"readonly/></td>\r\n");
      out.write("\t\t<td bgcolor=\"#f1f1f1\">日期：</td>\r\n");
      out.write("\t\t<td bgcolor=\"#f1f1f1\"><input type=\"date\" id=\"date\" name=\"instore.date\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<input type=\"hidden\" id=\"op\" name=\"bian\"/>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\" bgcolor=\"#f1f1f1\">编号：</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td  bgcolor=\"#f1f1f1\" id=\"idtext\"><input  type=\"button\" onclick=\"show(this);\" value=\"获取\"readonly/></td>\r\n");
      out.write("\t\t<td bgcolor=\"#f1f1f1\">姓名：</td>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<td bgcolor=\"#f1f1f1\"><input id=\"nametext\"  style=\"background-color:#f1f1f1\"type=\"text\" value=\"\"readonly/></td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\"  bgcolor=\"#f1f1f1\" >地址：</td>\r\n");
      out.write("\t\t<td colspan=\"3\"  bgcolor=\"#f1f1f1\"><input id=\"addresstext\"  style=\"background-color:#f1f1f1\" value=\"\" type=\"text\"/ size=\"55\"readonly></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"4\">交易明细</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" align=\"center\" bgcolor=\"#f1f1f1\">名称</td>\r\n");
      out.write("\t\t<td colspan=\"2\" align=\"center\" bgcolor=\"#f1f1f1\">重量</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" align=\"center\" bgcolor=\"#f1f1f1\">小麦</td>\r\n");
      out.write("\t\t<td colspan=\"2\" bgcolor=\"#f1f1f1\"><input type=\"text\"name=\"instore.weight\" id=\"rawstore\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" align=\"center\"><input type=\"button\"onclick=\"Check();\"  value=\"保存\"/></td>\r\n");
      out.write("\t\t<td colspan=\"2\" align=\"center\"><input type=\"button\" value=\"取消\" onclick=\"test();\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
