/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-01-11 06:42:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class useflour_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1515652906491L));
    _jspx_dependants.put("jar:file:/E:/7组/.metadata/.me_tcat85/webapps/Flour/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279401888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'useflour.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction test(){\r\n");
      out.write(" var url = \"flouruse\";\r\n");
      out.write(" window.location.href= url;\r\n");
      out.write("}\r\n");
      out.write("\t\t//弹出信息窗口\r\n");
      out.write("\t function show(obj){\r\n");
      out.write("       \r\n");
      out.write("        var x = window.screen.height;\r\n");
      out.write("    var y = window.screen.width;\r\n");
      out.write("    var h = 400;\r\n");
      out.write("    var w = 600;\r\n");
      out.write("    var model = \"title=word,resizable=yes,scrollbars=no,height=\" + h + \",width=\" + w + \",status=no,toolbar=no,menubar=no,location=no,top=\" + (x-h)/2 + \",left=\" + (y-w)/2;\r\n");
      out.write("    var url = \"\";\r\n");
      out.write("\r\n");
      out.write("    url = \"inquireclient.jsp\";//弹出窗口的页面内容\r\n");
      out.write("    var oOpen = window.open(url,\"add\",model);\r\n");
      out.write("    oOpen.focus();\r\n");
      out.write("    }\r\n");
      out.write("function Check(){\r\n");
      out.write("   \r\n");
      out.write("   var n1=document.getElementById(\"uweight\").value;\r\n");
      out.write("   var n2=document.getElementById(\"op\").value;\r\n");
      out.write("   var n3=document.getElementById(\"date\").value;\r\n");
      out.write("   var n4=document.getElementById(\"addresstext\").value;\r\n");
      out.write(" \r\n");
      out.write("      var n5=document.getElementById(\"nametext\").value;\r\n");
      out.write("      var n6=document.getElementById(\"price\").value;\r\n");
      out.write("      var erroring=\"\";\r\n");
      out.write("var select=document.getElementById(\"sele\");\r\n");
      out.write("     var s=select.options[select.selectedIndex].innerHTML;\r\n");
      out.write("     document.getElementById(\"option\").value=s;\r\n");
      out.write("      if(n1==\"\"||n1==null){\r\n");
      out.write("        erroring+=\"请输入领取面粉重量!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n2==\"\"||n2==null){\r\n");
      out.write("     erroring+=\"请输入客户编号!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n3==\"\"||n3==null){\r\n");
      out.write("  erroring+=\"请输入日期!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n4==\"\"||n4==null){\r\n");
      out.write("  erroring+=\"请输入客户地址!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" if(n5==\"\"||n5==null){\r\n");
      out.write("  erroring+=\"请输入客户姓名!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  if(n6==\"\"||n6==null){\r\n");
      out.write("  erroring+=\"请输入加工费!\"+'\\n';\r\n");
      out.write("  }\r\n");
      out.write("  if(erroring.length!=0){\r\n");
      out.write("  alert(erroring);\r\n");
      out.write("  return false;\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  }else{\r\n");
      out.write("  alert(\"保存成功！\");\r\n");
      out.write("     document.form1.submit();    \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("function cha(){\r\n");
      out.write("var cha;\r\n");
      out.write("if(document.getElementById(\"pay\").value>document.getElementById(\"realpay\").value){\r\n");
      out.write("cha=document.getElementById(\"pay\").value-document.getElementById(\"realpay\").value;\r\n");
      out.write("//var select=document.getElementById(\"selectid\");\r\n");
      out.write("//var s=select.options[select.selectedIndex].value;\r\n");
      out.write("document.getElementById(\"cha\").value=cha;\r\n");
      out.write("document.getElementById(\"selectid\").value=3;\r\n");
      out.write("}\r\n");
      out.write("if(document.getElementById(\"pay\").value<document.getElementById(\"realpay\").value){\r\n");
      out.write("cha=document.getElementById(\"realpay\").value-document.getElementById(\"pay\").value;\r\n");
      out.write("//var select=document.getElementById(\"selectid\");\r\n");
      out.write("//var s=select.options[select.selectedIndex].value;\r\n");
      out.write("document.getElementById(\"cha\").value=cha;\r\n");
      out.write("document.getElementById(\"selectid\").value=2;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("  function sel(){\r\n");
      out.write("  \tvar a = document.getElementById(\"sele\");\r\n");
      out.write("  \tvar index=a.selectedIndex;\r\n");
      out.write("\r\n");
      out.write("  \tdocument.getElementById(\"note\").value=a.options[index].value;\r\n");
      out.write("  \tdocument.getElementById(\"bran\").value=0.0;\r\n");
      out.write("  \tdocument.getElementById(\"flour\").value=0.0;\t\r\n");
      out.write("  \t\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("  function cal(){\r\n");
      out.write("  var uw=document.getElementById(\"uweight\").value;\r\n");
      out.write("  var n=document.getElementById(\"note\").value;\r\n");
      out.write("  document.getElementById(\"rawweight\").value=uw/(0.01*n);\r\n");
      out.write("  document.getElementById(\"branweight\").value=uw/(0.01*n)-uw;\r\n");
      out.write("  var price=document.getElementById(\"price\").value;\r\n");
      out.write("  document.getElementById(\"sum\").value=price*uw;\r\n");
      out.write("  \r\n");
      out.write("document.getElementById(\"pay\").value=price*uw;\r\n");
      out.write("document.getElementById(\"realpay\").value=price*uw;\r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("\t\t </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"28278\",secure:\"28283\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  \r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-35\" data-genuitec-path=\"/Flour/WebRoot/useflour.jsp\">\r\n");
      out.write("  <strong style=\"font-size:25px\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-35\" data-genuitec-path=\"/Flour/WebRoot/useflour.jsp\">原粮兑换面粉|</strong>面粉领用\r\n");
      out.write("   <form id=\"form1\"name=\"form1\" action=\"addflouruse\">\r\n");
      out.write("   <center>\r\n");
      out.write("    <table border=\"1\" width=\"700\" cellspacing=\"0\" bordercolor=\"#8EE1F6\">\r\n");
      out.write("    <input type=\"hidden\" id=\"op\" name=\"bian\"/>\r\n");
      out.write("      <input type=\"hidden\" id=\"option\" name=\"option\"/>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td  colspan=\"9\" align=\"center\" >面粉领用</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"2\" align=\"right\" bgcolor=\"#f1f1f1\">凭证编号：</td>\r\n");
      out.write("    <td colspan=\"3\" bgcolor=\"#f1f1f1\"><input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"type=\"text\" style=\"width:263px\" name=\"useflour.eid\" readonly /></td>\r\n");
      out.write("    <td colspan=\"1\" align=\"right\" bgcolor=\"#f1f1f1\"> 日期：</td>\r\n");
      out.write("    <td colspan=\"3\" bgcolor=\"#f1f1f1\"><input type=\"date\"  style=\"width:260px\" name=\"useflour.date\" id=\"date\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td  colspan=\"2\" align=\"right\" bgcolor=\"#f1f1f1\">客户编号：</td>\r\n");
      out.write("    <td id=\"idtext\" colspan=\"3\" bgcolor=\"#f1f1f1\"><input type=\"button\"  onclick=\"show(this);\"value=\"获取\" name=\"clientid\"/></td>\r\n");
      out.write("    <td  colspan=\"1\" align=\"right\" bgcolor=\"#f1f1f1\"> 姓名：</td>\r\n");
      out.write("    <td  colspan=\"3\" bgcolor=\"#f1f1f1\"><input id=\"nametext\" type=\"text\" style=\"width:260px;background-color:#f1f1f1\" name=\"clientname\"readonly/></td>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"2\" align=\"right\"  bgcolor=\"#f1f1f1\">地址：</td>\r\n");
      out.write("    <td  colspan=\"7\"  bgcolor=\"#f1f1f1\"><input id=\"addresstext\"   style=\"width:612px;background-color:#f1f1f1\"type=\"text\" name=\"clientaddress\" readonly/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr><td colspan=\"9\" align=\"center\">交易明细</td></tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td width=\"30\"  bgcolor=\"#f1f1f1\">小麦库存</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">面粉类型</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">领用面粉重量</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">加工费￥</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">出粉率</td>\r\n");
      out.write("    <td bgcolor=\"#f1f1f1\">加工小麦</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">出库麸皮</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">总价￥</td>\r\n");
      out.write("    <td  bgcolor=\"#f1f1f1\">领用麸皮</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td bgcolor=\"#f1f1f1\"><input  style=\"width:80px;background-color:#f1f1f1\"type=\"text\" id=\"rawstore\" readonly/></td>\r\n");
      out.write("    <td bgcolor=\"#f1f1f1\"><select  onchange=\"sel();\" id=\"sele\">\r\n");
      out.write("\t<option>产品种类</option>\r\n");
      out.write("\t");
      if (_jspx_meth_s_005fiterator_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td>\r\n");
      out.write("    <td ><input style=\"width:95px\" type=\"text\"id=\"uweight\" name=\"useflour.uweight\"/></td>\r\n");
      out.write("    <td><input style=\"width:80px\" id=\"price\" type=\"text\" name=\"useflour.price\"/></td>\r\n");
      out.write("    <td><input style=\"width:80px;background-color:#f1f1f1\" type=\"text\" id=\"note\" name=\"useflour.rate\" readonly/></td>\r\n");
      out.write("    <td><input  style=\"width:80px;background-color:#f1f1f1\"type=\"text\" id=\"rawweight\" onBlur=\"cal();\" name=\"useflour.rawweight\"readonly/></td>\r\n");
      out.write("    <td><input  style=\"width:80px;background-color:#f1f1f1\"type=\"text\" id=\"branweight\" name=\"useflour.branweight\"readonly/></td>\r\n");
      out.write("    <td><input  style=\"width:80px;background-color:#f1f1f1\"id=\"sum\" type=\"text\" name=\"useflour.sum\"readonly/></td>\r\n");
      out.write("    <td bgcolor=\"#f1f1f1\"><input style=\"width:80px\" type=\"checkbox\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <tr><td colspan=\"9\" align=\"center\">交易信息</td></tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"3\" align=\"right\" bgcolor=\"#f1f1f1\">应收金额￥：</td>\r\n");
      out.write("    <td colspan=\"2\" bgcolor=\"#f1f1f1\"><input type=\"text\" id=\"pay\" name=\"pay\"readonly/></td>\r\n");
      out.write("    <td colspan=\"2\" align=\"right\">实收金额￥：</td>\r\n");
      out.write("    <td colspan=\"2\" onclick=\"cha();\"><input type=\"text\"id=\"realpay\" name=\"realpay\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"3\" align=\"right\">收付状态：</td>\r\n");
      out.write("    <td colspan=\"2\"><select id=\"selectid\">\r\n");
      out.write("                    <option  selected>收支平衡</option>\r\n");
      out.write("                    <option value=2>支大于收</option>\r\n");
      out.write("                    <option value=3>收大于支</option></select></td>\r\n");
      out.write("    <td colspan=\"2\" align=\"right\" bgcolor=\"#f1f1f1\">收付差额￥：</td>\r\n");
      out.write("    <td colspan=\"2\" bgcolor=\"#f1f1f1\"><input type=\"text\" id=\"cha\" value=\"0\"readonly/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"5\" align=\"right\"><input type=\"button\" onclick=\"Check();\"value=\"保存\"/></td>\r\n");
      out.write("    <td colspan=\"4\"><input type=\"button\" value=\"取消\" onclick=\"test();\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    </table>\r\n");
      out.write("    </center>\r\n");
      out.write("    </form>\r\n");
      out.write("  \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fiterator_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f0 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    try {
      _jspx_th_s_005fiterator_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fiterator_005f0.setParent(null);
      // /useflour.jsp(178,1) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f0.setValue("#request.list");
      // /useflour.jsp(178,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f0.setVar("l");
      int _jspx_eval_s_005fiterator_005f0 = _jspx_th_s_005fiterator_005f0.doStartTag();
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_s_005fiterator_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_s_005fiterator_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("\t<option name=\"flourtype\" value=\"");
          if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
            return true;
          out.write('"');
          out.write('>');
          if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
            return true;
          out.write("</option>\r\n");
          out.write("\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_s_005fiterator_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fiterator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue.reuse(_jspx_th_s_005fiterator_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    try {
      _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
      // /useflour.jsp(179,33) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f0.setValue("#l.note");
      int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
      if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    try {
      _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
      // /useflour.jsp(179,64) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f1.setValue("#l.typename");
      int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
      if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    }
    return false;
  }
}
